audio_dir: E:/Py_Project/multi-audio_video_combiner/script/temp/cut
audio_file_format: mp3
def_farm: 28
default_audio_dir: F:/LiShuiHan/逆水寒/artist/res/ResourceForPlayer/userdata/external_sound
farm_output: 60
game_dir: F:/LiShuiHan/逆水寒/artist/res
movie_save_dir: E:/Py_Project/multi-audio_video_combiner/千年药灵跑路了_第13集.movie
render_dir: E:/大宋映画/Sequence_Frame_OutPut/8.16Homework/02
video_time: 105.78
